### ISSUE TITLE
Complete Project

### ISSUE THREAD

**Issue by nsanden** [nsanden/astrology-calculator#1]
Project name Astrology Calculator

We want to basically copy the functionality found here: http://www.calculatorcat.com/free_calculators/astrological_sign.phtml

Design wise, we want bootstrap of course. If you feel inspired, come up with your own design, otherwise just copy the same type of look we have here: https://headlinecapitalization.com/

Requirements:
- [ ] Yii basic app (no db needed)
- [ ] Facebook, twitter, G+ buttons like we have on headlinecapitalization
- [ ] Reserve some area where we can write in some text paragraphs for SEO purposes

**Comment by prominentapps** [comment]
Sorry ... :( 

Didn't get last point .. 

Reserve some area where we can write in some text paragraphs for SEO purposes

**Comment by nsanden** [comment]
Just means, we want to be able to have room on the web page to write in some text. For example, on https://headlinecapitalization.com see:
![untitled](https://cloud.githubusercontent.com/assets/2072064/9943653/99a2406c-5d37-11e5-98aa-b10ad2dcd42a.png)

**Comment by prominentapps** [comment]
Ohh.. You mean to display some static text .. 

I thought something like use can write/post :( :(  My mistake :(

**Comment by prominentapps** [comment]
Should I log this into beachinsoft?

**Comment by nsanden** [comment]
Log it under the 1s0s.com/SavingAdvice.com one actually

**Comment by prominentapps** [comment]
Please check and let me know .. 

1. I've copied js logic (for finding sing) from the referring site. 

2. I've not considered any validations yet for birth date value. Let me know which validations we need to consider.. 

3. Facebook, twitter, G+ buttons like we have on headlinecapitalization - Not added yet.. Will add it soon ..

**Comment by nsanden** [comment]
Let's use some basic dropdowns like http://www.rithychhen.com/jquery/birthdaypicker

**Comment by prominentapps** [comment]
I applied basic dropdowns.. Let me know if we need to consider any restriction for invalid date selection or displaying validation message for invalid selection.. 

For now, If the selection is invalid then I'm just displaying **this smiley** :(  for Sun Sign & Chinese Sign values ..
