### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by savingadvice** [nsanden/astrology-calculator#7]
similar to this: http://www.online-stopwatch.com/countdown-timer/ but better :)

**Comment by prominentapps** [comment]
I worked on this issue.  

I tried to complete major of the things but considering milliseconds in timer doesn't work properly.. For now I've commented milliseconds related to code and it all works fine Hours, Mins & Secs.. 

You can check it from site/timer ..    

Let me know if you find any clue for fixing milliseconds related issue..
